# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

jobs:
- job: RunHelloBat
  displayName: 'Run C:\\hello.bat on local agent'
  steps:
  - script: |
      echo Running C:\hello.bat...
      call C:\hello.bat
    displayName: 'Run BAT from C drive'


