trigger: none

parameters:
- name: outputFileName
  type: string
  default: output.txt

pool:
  name: Default

jobs:
- job: RunBatFileWithParam
  steps:
  - script: |
      echo Running hello.bat with output file: ${{ parameters.outputFileName }}
      cd $(Build.SourcesDirectory)
      cmd /c "D:\hello.bat ${{ parameters.outputFileName }}"
    displayName: 'Run hello.bat with output file parameter'

  - script: |
      echo Copying output file to D drive...
      copy "$(Build.SourcesDirectory)\${{ parameters.outputFileName }}" "D:\${{ parameters.outputFileName }}"
    displayName: 'Copy output file to D:\'
