trigger: none

parameters:
- name: outputFileName
  type: string
  default: ''

pool:
  name: Default

jobs:
- job: RunBatFileWithParam
  displayName: 'Run hello.bat and handle result'
  steps:
  - script: |
      echo ============================================
      echo [INFO] Running hello.bat with output file: ${{ parameters.outputFileName }}
      echo ============================================

      rem Gọi file .bat và truyền tham số
      call D:\hello.bat ${{ parameters.outputFileName }}

      rem Kiểm tra mã lỗi trả về
      if errorlevel 1 (
          echo ##[error] hello.bat failed with exit code %errorlevel%
          exit /b %errorlevel%
      ) else (
          echo ##[section]hello.bat completed successfully.
      )
    displayName: 'Execute hello.bat with parameter and check result'
