trigger: none

parameters:
- name: outputFileName
  type: string
  default: output.txt

pool:
  name: Default

jobs:
- job: RunBatFileWithParam
  steps:
  - script: |
      echo Running hello.bat with output file: ${{ parameters.outputFileName }}
      cmd /c "D:\hello.bat ${{ parameters.outputFileName }}"
    displayName: 'Run hello.bat with output file parameter'
