trigger: none  # Chạy thủ công

parameters:
- name: batFileName
  type: string
  default: hello1.bat  # Tên mặc định

pool:
  name: Default  # Self-hosted Windows agent

jobs:
- job: RunBatFile
  displayName: 'Run .BAT file by filename input'
  steps:
  - script: |
      echo Running file: D:\${{ parameters.batFileName }}
      cmd /c "D:\${{ parameters.batFileName }}"
    displayName: 'Run .bat file from D:\'
