trigger:
- main

pool:
  name: Default  # Self-hosted Windows agent pool

jobs:
- job: RunHelloBat
  displayName: 'Run D:\\hello.bat on local agent'
  steps:
  - script: |
      echo Running D:\hello.bat...
      start /wait "" "D:\hello.bat"
    displayName: 'Run BAT from D drive'
