trigger:
- main

pool:
  name: Default  # Self-hosted Windows agent pool

jobs:
- job: RunHelloBat
  displayName: 'Run D:\\hello.bat using cmd on local agent'
  steps:
  - script: |
      cmd /c "D:\hello.bat"
    displayName: 'Run BAT from D drive using cmd'
